### ISSUE TITLE
Exception when using ResXResourceWriter

### ISSUE THREAD

**Issue by borgdylan** [farlee2121/ResXResourceReader.NetStandard#1]
When using ResXResourceWriter I get the following:
```
System.Resources.MissingManifestResourceException: Could not find the resource "Fourstarzz.CopyTranslationsToJson.ResxReader.SR.resources" among the resources "System.Resources.NetStandard.SR.resources" embedded in the assembly "System.Resources.NetStandard", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
```

Please fix the following line to use the name "System.Resources.NetStandard.SR.resources" instead of "Fourstarzz.CopyTranslationsToJson.ResxReader.SR.resources": 
https://github.com/farlee2121/ResXResourceReader.NetStandard/blob/54985ec8aa45e6cf9c0c0e282c778dbad5097c67/System.Resources.NetStandard/SR.Designer.cs#L42

**Comment by farlee2121** [comment]
Woops, that one slipped through the net. I'll try to get a new version out by tomorrow

**Comment by farlee2121** [comment]
I also may need to look into my notification settings, github didn't send me an email about your issue  😒

**Comment by farlee2121** [comment]
A new version is being validated by Nuget as we speak. Should be out shortly.  

Something to note, this error only shows up when it's trying to read a different error message from the SR resource file. This means that the code that threw this exception will probably throw a new exception with the new version, just with better details.

Thanks for the report!
