### ISSUE TITLE
strong naming

### ISSUE THREAD

**Issue by pirobox** [farlee2121/ResXResourceReader.NetStandard#4]
Hi,
    would it be possible to generate the assembly System.Resources.NetStandard with a strong name?

regards,

**Comment by farlee2121** [comment]
I'm not familiar with generating strongly named assemblies. I'll have to do some reading.

Do you have any recommended resources?

**Comment by farlee2121** [comment]
I peeked around, and I think I figured it out. 
https://www.nuget.org/packages/ResXResourceReader.NetStandard.StrongName/

Please let me know if this works for you.
