### ISSUE TITLE
Resources with reference to ResXNullRef try to load System.Windows.Forms

### ISSUE THREAD

**Issue by AdrianKokot** [farlee2121/ResXResourceReader.NetStandard#9]
I can see that `ResXFileRef` was appropriately handled in [ResXConstants](https://github.com/farlee2121/ResXResourceReader.NetStandard/blob/110c7e08ac83c90d6b207e8825d66fa9d9974f32/System.Resources.NetStandard/ResxConstants.cs#L11) and [ResXDataNode](https://github.com/farlee2121/ResXResourceReader.NetStandard/blob/110c7e08ac83c90d6b207e8825d66fa9d9974f32/System.Resources.NetStandard/ResXDataNode.cs#L959), but `ResXNullRef` didn't. 

@farlee2121 Is there any particular reason why is that?

The issue I'm facing is that I'm loading dynamically created resource file where I can see that type `ResXNullRef` was loaded:

```xml
  <assembly alias="System.Windows.Forms" name="System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="Some_Property" type="System.Resources.ResXNullRef, System.Windows.Forms">
    <value />
  </data>
```

The `ResXDataNode` is trying to load assembly `System.Windows.Forms` in that case. I believe that using the same technique as with `RasXFileRef` would prevent that issue. I can do PR, but I need information whether handling of the `ResXNullRef` was not implemented for a reason that I can't see right now.

**Comment by farlee2121** [comment]
There's not a specific reason `ResXNullRef` isn't handled, it just slipped through the cracks.
A PR would be much appreciated!

**Comment by AdrianKokot** [comment]
@farlee2121 PR created :)

**Comment by farlee2121** [comment]
Version 1.3.0 is up with the fix
